Update README.md
DimaStoyanov/Ifmo-code pull request #6
Opened 2019-01-17 19:40 UTC by MikhailovNikita

Who tf is not able to rotate a photo in 2019?

2019-01-18 21:24 UTC, SamarinAnton approved these changes

2019-01-19 11:13 UTC, nariman reviewed
@MikhailovNikita What about photo with statements for lab5?

2019-01-19 12:18 UTC, DimaStoyanov requested changes
Like Nariman mentioned, it would be great if you update rotate photo in 5 lab too

2019-02-23 10:43 UTC, nariman commented
@DimaStoyanov 
![image](https://user-images.githubusercontent.com/6004127/53285396-90625280-3768-11e9-88fd-48582e613248.png)

2019-02-23 10:45 UTC, nariman approved these changes

2019-02-23 12:01 UTC, DimaStoyanov approved these changes

2019-02-23 12:01 UTC, merged